name: clean_arch_tdd_course
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^1.0.0
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.2
  internet_connection_checker_plus: ^2.0.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
